#!/bin/bash

### Blackbridge imagery workflow
# Download sample imagery at: http://blackbridge.com/rapideye/myrapideye/index.html
# This script is specific to the 3B Ortho Take product of Brazil's Federal District
# but can be adapted to many others easily

for var in $@; do
    export var=${var%.tif}

    gdalwarp \
    -s_srs EPSG:32723 \
    -t_srs EPSG:3857 \
    -r cubic \
    -dstnodata 0 \
    ${var}.tif \
    ${var}-3857.tif 

    gdal_translate \
    -scale 0 65535 0 255 \
    -ot Byte \
    -b 3 \
    -b 2 \
    -b 1 \
    -co photometric=rgb \
    -a_srs EPSG:3857 \
    -a_nodata "0 0 0" \
    -of GTiff \
    ${var}-3857.tif \
    ${var}-3857-rgb.tif

    nearblack \
    -o  ${var}-3857-rgb-nb.tif \
    -of GTiff \
    ${var}-3857-rgb.tif;
done


gdal_merge.py \
-o merged.tif \
-n 0 \
*nb.tif

convert -sigmoidal-contrast 30,8% -modulate 100,125 merged.tif merged-color.tif

gdal_translate \
-a_srs EPSG:3857 \
-a_nodata "0 0 0" \
merged-color.tif \
processed.tif


listgeo -tfw merged.tif
mv merged.tfw processed.tfw
gdal_edit.py -a_srs EPSG:3857 processed.tif


for var in $@; do
    export var=${var%.tif}
    rm ${var}-3857.tif
    rm ${var}-3857-rgb.tif
    rm ${var}-3857-rgb.tif.aux.xml
    rm ${var}-3857-rgb-nb.tif
    rm merged.tif
    rm merged-color.tif
    rm processed.tfw;
done